SELECT UGU.USER_ID USER_ID, UGU.NICKNAME NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER UGU
JOIN USED_GOODS_BOARD UGB
ON UGU.USER_ID = UGB.WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES