SELECT SUM(HG.SCORE) AS SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_DEPARTMENT HD
INNER JOIN HR_EMPLOYEES HE
ON HD.DEPT_ID = HE.DEPT_ID
INNER JOIN HR_GRADE HG
ON HG.EMP_NO = HE.EMP_NO

GROUP BY HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;